services:
  database:
    image: postgres:17-alpine
    restart: always
    environment:
       POSTGRES_PASSWORD: secret@pass
       POSTGRES_USER: root
       POSTGRES_DB: finance
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: