spring:
  application:
    name: finance

  profiles:
    active: ${PROFILE:dev}


server:
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /doc
    filter: true
    operationsSorter: method
    tags-sorter: none

security:
  cors:
    mapping: "/**"
    allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
    allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
    allowed-headers: ${CORS_ALLOWED_HEADERS:*}
    allow-credentials: ${CORS_CREDENTIALS:false}