spring:
  application:
    name: management-finance-api
  profiles:
    active: ${PROFILE:dev}
  jpa:
    mapping-resources:
      - META-INF/orm-category.xml
      - META-INF/orm-balance.xml

management:
  endpoints:
    web:
      exposure:
        include: openapi, swagger-ui, health
springdoc:
  swagger-ui:
    path: /

server:
  servlet:
    context-path: /api