spring:
  application:
    name: finance
  datasource:
    url:  jdbc:h2:mem:teste
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2