spring:
  datasource:
    url: ${DB_URL}
    username: root
    password: secret@pass
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    url: ${DB_URL}
    user: root
    password: secret@pass
    locations: classpath:db/migration
    default-schema: public

  devtools:
      restart:
        enabled: true
        poll-interval: 1s
        quiet-period: 500ms

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%-20thread] [traceId=%-21X{traceId}] %highlight(%-5level) %-40logger{36} - %msg%n"
