spring:
  application:
    name: management-finance-api

  datasource:
    url: jdbc:postgresql://localhost:5432/easy-finace
    username: root
    password: postgres
    driver-class-name: org.postgresql.Driver


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    url: jdbc:postgresql://localhost:5432/easy-finace
    user: root
    password: postgres
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: openapi, swagger-ui
springdoc:
  swagger-ui:
    path: /doc/v1

server:
  servlet:
    context-path: /api
  port: 8080

security:
  jwt:
    #expire-time in seconds
    expire-time: 30
    issuer: delimajonatas875@gmail.com
    secret: b2Hj0H1|@4OavVWdCd1qzEj7'022p\S9Kh
  jwt-refresh:
    #expire-time in seconds
    expire-time: 60
