spring:
  application:
    name: management-finance-api
  profiles:
    active: ${PROFILE:dev}

management:
  endpoints:
    web:
      exposure:
        include: openapi, swagger-ui
springdoc:
  swagger-ui:
    path: /doc/v1

server:
  servlet:
    context-path: /api