services:
  nginx:
    image: nginx:stable-alpine3.23
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    restart: unless-stopped
    networks:
      - appnet

  api:
    image: jonat4s/finance-api:2ef0d8f
    environment:
      PROFILE: ${PROFILE}
      SPRING_DATABASE_URL: ${SPRING_DATABASE_URL}
      SPRING_DATABASE_USERNAME: ${SPRING_DATABASE_USERNAME}
      SPRING_DATABASE_PASSWORD: ${SPRING_DATABASE_PASSWORD}
      SECURITY_JWT_ISSUE: ${SECURITY_JWT_ISSUE}
      SECURITY_ACCESS_TOKEN_SECRET: ${SECURITY_ACCESS_TOKEN_SECRET}
      SECURITY_ACCESS_TOKEN_EXPIRE_TIME: ${SECURITY_ACCESS_TOKEN_EXPIRE_TIME}
      SECURITY_REFRESH_TOKEN_SECRET: ${SECURITY_REFRESH_TOKEN_SECRET}
      SECURITY_ACCESS_REFRESH_EXPIRE_TIME: ${SECURITY_ACCESS_REFRESH_EXPIRE_TIME}
      JAVA_TOOLS_OPTIONS: >
        -XX:InitialRAMPercentage=25
        -XX:MaxRAMPercentage=65 
    restart: unless-stopped
    expose:
      - 8080
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f" , "http://localhost:8080/actuator/health"]
      start_period: 40s
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

