FROM eclipse-temurin:21-alpine-3.23

WORKDIR /app

RUN apk add --no-cache entr

COPY pom.xml .

COPY mvnw .

COPY .mvn .mvn

RUN chmod +x mvnw

RUN ./mvnw -DskipTests dependency:go-offline

COPY . .

EXPOSE 8080

CMD ["sh", "entrypoint.sh"]